server.port=8082
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# next two line are weird - recommend use both if u want lower-case service-names.
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# note:
#   Old config item "spring.cloud.gateway.discovery.locator.enabled"
#   replaced by "spring.cloud.gateway.server.webflux.discovery.locator.enabled".
#spring.cloud.gateway.discovery.locator.enabled=true

